/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-11 14:52:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View.Home.Theme;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html ./View/Home/Public \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Magic fox</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./View/Home/Public/CSS/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"head\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<img src=\"./View/Home/Public/Image/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"about\">\r\n");
      out.write("\t\t\t<a href=\"\">Attention</a>\r\n");
      out.write("\t\t\t<a href=\"\">Log</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"message\">\r\n");
      out.write("\t\t\t<p>let us change the world</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"join\">\r\n");
      out.write("\t\t\t<p><a href=\"\">Join Me And Enjoy The World</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!--结束head部分-->\r\n");
      out.write("\t\t<!--开始nav部分-->\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<img src=\"./View/Home/Public/Image/study.png\" class=\"nav-./View/Home/Public/Image\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"nav-a\">study</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<img src=\"./View/Home/Public/Image/work.png\" class=\"nav-./View/Home/Public/Image\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"nav-a\">work</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<img src=\"./View/Home/Public/Image/life.png\" class=\"nav-./View/Home/Public/Image\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"nav-a\">life</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--结束nav部分-->\r\n");
      out.write("\t<!--开始main部分-->\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t");
      model.home.Theme sql = null;
      sql = (model.home.Theme) _jspx_page_context.getAttribute("sql", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (sql == null){
        sql = new model.home.Theme();
        _jspx_page_context.setAttribute("sql", sql, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		ResultSet study,work,life;
		study=sql.getStudy();
		work=sql.getWork();
		life=sql.getLife();
	
      out.write("\r\n");
      out.write("\t\t<div class=\"clude\">\r\n");
      out.write("\t\t\t<div class=\"article study\">\r\n");
      out.write("\t\t\t\t<h1>stay hungry , stay foolish</h1>\r\n");
      out.write("\t\t\t\t");
while(study.next()) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=");
      out.print("'theme "+study.getString(3)+"'" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<img src=");
      out.print("'./View/Home/Public/Image/Index/"+study.getString(3)+"'.jpg" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<p class=\"title\"><a href=\"\">");
      out.print(study.getString(4) );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print(study.getString(5));
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"article work\">\r\n");
      out.write("\t\t\t\t<h1>Work is worth doing of worth doing well</h1>\r\n");
      out.write("\t\t\t\t");
while(work.next()) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=");
      out.print("'theme "+work.getString(3)+"'" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<img src=");
      out.print("'./View/Home/Public/Image/Index/"+work.getString(3)+"'.jpg" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<p class=\"title\"><a href=\"\">");
      out.print(work.getString(4) );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print(work.getString(5));
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"article life\">\r\n");
      out.write("\t\t\t\t<h1>Love rules my kingdom without a sword</h1>\r\n");
      out.write("\t\t\t\t");
while(life.next()) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=");
      out.print("'theme "+life.getString(3)+"'" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<img src=");
      out.print("'./View/Home/Public/Image/Index/"+life.getString(3)+"'.jpg" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t<p class=\"title\"><a href=\"\">");
      out.print(life.getString(4) );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print(life.getString(5));
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--main部分结束-->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"\">About</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"\">Contact</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"\">More</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<p>Direct by <a href=\"\">Summit</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
